import Head from 'next/head'
import axios from "axios";
import React, { useState, useEffect } from "react";

import Dashboard from "./dashboard/index";
import Signin from "./signin/index";

export default function Home() {
  const [authenticated, setAuth] = useState(false);
  
  useEffect(()=> {
    if(localStorage.getItem("session")){
      setAuth(true);
    }
    axios.post(`${process.env.BASE_URL}analytics`)
    .then(res => console.log("Success"))
      .catch(err => console.log(err))
  }, [authenticated]);
  
  return (
    <div>
       <Head>
        <title>MimicOS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Logo.png" />
      </Head>
      {!authenticated && <Signin />}
      {authenticated && <Dashboard />}
    </div>
  )
}
